version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - run:
          name: Check Go version
          command: go version
      - run:
          name: Check GOPATH
          command: |
            go env GOPATH
            go env GOROOT
